apiVersion: v1
kind: Service
metadata:
  name: spin-gate
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-gate
spec:
  selector:
    app: spin
    cluster: spin-gate
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084

---

apiVersion: v1
kind: Secret
metadata:
  name: spin-gate-config-files
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-gate
type: Opaque
stringData:
  spinnaker.yml: |
    services:
      clouddriver:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver.spinnaker:7002
        enabled: true
      clouddriverCaching:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-caching.spinnaker:7002
        enabled: false
      clouddriverRo:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-ro.spinnaker:7002
        enabled: false
      clouddriverRoDeck:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-ro-deck.spinnaker:7002
        enabled: false
      clouddriverRw:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-rw.spinnaker:7002
        enabled: false
      deck:
        host: 0.0.0.0
        port: 9000
        baseUrl: http://localhost:9000
        enabled: true
      echo:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo.spinnaker:8089
        enabled: true
      echoScheduler:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo-scheduler.spinnaker:8089
        enabled: false
      echoWorker:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo-worker.spinnaker:8089
        enabled: false
      fiat:
        host: 0.0.0.0
        port: 7003
        baseUrl: http://spin-fiat.spinnaker:7003
        enabled: false
      front50:
        host: 0.0.0.0
        port: 8080
        baseUrl: http://spin-front50.spinnaker:8080
        enabled: true
      gate:
        host: 0.0.0.0
        port: 8084
        baseUrl: http://localhost:8084
        enabled: true
      igor:
        host: 0.0.0.0
        port: 8088
        baseUrl: http://spin-igor.spinnaker:8088
        enabled: false
      kayenta:
        host: 0.0.0.0
        port: 8090
        baseUrl: http://spin-kayenta.spinnaker:8090
        enabled: false
      orca:
        host: 0.0.0.0
        port: 8083
        baseUrl: http://spin-orca.spinnaker:8083
        enabled: true
      redis:
        host: 0.0.0.0
        port: 6379
        baseUrl: redis://spin-redis.spinnaker:6379
        enabled: false
      rosco:
        host: 0.0.0.0
        port: 8087
        baseUrl: http://spin-rosco.spinnaker:8087
        enabled: false
      monitoringDaemon:
        host: 0.0.0.0
        port: 8008
        baseUrl: http://spin-monitoring-daemon.spinnaker:8008
        enabled: false

    global.spinnaker.timezone: America/Los_Angeles

  gate.yml: |
    armory:
      registrationId: armory-quick-spin-install

    cors: {}
    google: {}

    integrations:
      gremlin:
        baseUrl: https://api.gremlin.com/v1
        enabled: false

    security:
      basic:
        enabled: true
      user: {}

    server:
      address: 0.0.0.0
      port: "8084"
      ssl:
        enabled: false

    spectator:
      applicationName: ${spring.application.name}
      webEndpoint:
        enabled: false

    spinnaker:
      extensibility:
        plugins: {}
        plugins-root-path: /opt/gate/plugins
        repositories: {}
        strict-plugin-loading: false

  gate-local.yml: |
    archaius:
      fixedDelayPollingScheduler:
        delayMills: 2147483647
        initialDelayMills: 2147483647

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-gate
  namespace: spinnaker
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"gate"'
  labels:
    app: spin
    cluster: spin-gate
    app.kubernetes.io/name: gate
    app.kubernetes.io/managed-by: armory
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 2.28.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-gate
  template:
    metadata:
      annotations: null
      labels:
        app: spin
        cluster: spin-gate
        app.kubernetes.io/name: gate
        app.kubernetes.io/managed-by: armory
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 2.28.0
    spec:
      containers:
      - name: gate
        image: docker.io/armory/gate:2.28.0
        ports:
        - containerPort: 8084
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8084/health
        livenessProbe: null
        startupProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8084/health
          initialDelaySeconds: 60
          periodSeconds: 5
        securityContext: null
        volumeMounts:
        - name: spin-gate-config-files
          mountPath: /opt/spinnaker/config
        env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-gate-config-files
        secret:
          secretName: spin-gate-config-files
